apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://8CA5BCBB49BF4D7BACECDCBD61429957.sk1.eu-west-1.eks.amazonaws.com
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJSWtiZDJIbWx4RVV3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBME1ESXhPVFUzTkRKYUZ3MHpOakF6TXpBeU1EQXlOREphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNzbmZ4TVA2YnhCdXpXRytFRnZxVXh6aUZKZ1AycTJaU2loQSswelMxUHJ2T3B1V0ZIbVVHSTZNYXAKc2pmT3d2bStJUG56TkNjdkt6YmFHdGp5WGIrMy9INk1XUGpHM1N5TGUvbHltdTJQLzA1UXJkV3p3d0hiNFlyMApNbEJFNXhhSWdZaWlGRkZCVzExWGVzSHRZUGRCekhpUkNzTlhIVW9IbU1zWjFsRkplZU5DMGlGckpEYWpDK3hXClVhL0l4TjhMTFVna2pWZno2ZXhBTEwvM0Y5d1VvRndZRy9GR0VhOEFlSkRWWm16M3laRTJjdnpYYmU5b29nZXIKUHQrdUNmZ202WmZzak1ZdWQ1akYxancxRk94WnVsL25Pckc3MEVXQkFtYnFLamhVb1V2N0lxa2dBS3Y5TnRzdgpwRUc5VEVyVTNSV291L1A4ZDNvZEhubVQyN2VUQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRU21uNXoySmYxbExxR2xwMk1GUEN1cVJaMWFEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ3FBTEg1T1VxbAphQVA1a3g4aUJPU1F5SExsVHNtZUI5bXdPMS9pdkUyUTg0d1k1Y1VPb3MzK3cxTmhoRFRuc3kxTHEvOGo0VzhoCmZFd0hnNzBpbFFYQXNRM2VQWTFlUm1Xb3NrZ2dCWWhiS1pLamhxZEZQaG84SlhMeitCM3RvRHVuNjdtQTNYUTQKbmp1bTc1RVY2MjdyWEMrc1BxcW5Nd1p1SGwvVDRPQk5jUlhNdHdYcHY1OWNxcGh5b3Rrd1BmNWFLcm5sc2NKZApFZXZROXVzOFcyTjZacGdhSHJFNWtzcnNvSHdNUXhiYkQ3TnpiL2ZQZGkvaWpOVHliN2RFL0M3bytrMHo4dDMyCno2bXVkRlFEQ2w1U1l4ZExGaXpSQUYrN3h1MnA2MEh0M2wyM3JIanROWlZIaWIwd3FpT2dUNmNUVWgzOEVFcmIKRm83U1pEVXVBVjdnCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  name: example-eks-cluster
contexts:
- context:
    cluster: example-eks-cluster
    user: example-eks-cluster
  name: example-eks-cluster
current-context: example-eks-cluster
users:
- name: example-eks-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: aws
      args:
        - eks
        - get-token
        - --cluster-name
        - example-eks-cluster
        - --region
        - eu-west-1
