apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: testsite

resources:
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/name: testsite
      app.kubernetes.io/component: web
    includeSelectors: true
