apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../base

patches:
  - path: argocd-cm-patch.yaml
  - path: argocd-cmd-params-cm-patch.yaml

# Resource customizations for production
# Uncomment and adjust based on your cluster size
# patchesStrategicMerge:
#   - argocd-server-deployment-patch.yaml
